apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Values.aadIdentityName }}
  namespace: hmi
spec:
  type: 0
  resourceID: {{ .Values.aadResourceId }}
  clientID: {{ .Values.aadClientId }}

---

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.aadIdentityName }}-binding
  namespace: hmi
spec:
  azureIdentity: {{ .Values.aadIdentityName }}
  selector: {{ .Values.aadIdentityName }}